// TASKS
export const TASKS_CREATING = 'TASKS_CREATING';
export const TASKS_CREATED = 'TASKS_CREATED';
export const TASKS_UPDATING = 'TASKS_UPDATING';
export const TASKS_UPDATED = 'TASKS_UPDATED';
export const TASKS_DELETING = 'TASKS_DELETING';
export const TASKS_DELETED = 'TASKS_DELETED';
export const TASKS_GETTING = 'TASKS_GETTING';
export const TASKS_GETTED = 'TASKS_GETTED';

// USERS
export const USERS_LOGGING_IN = 'USERS_LOGING_IN';
export const USERS_LOGGED_IN = 'USERS_LOGGED_IN';
export const USERS_REGISTERING = 'USERS_REGISTERING';
export const USERS_REGISTERED = 'USERS_REGISTERED';

// ERRORS
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const LOGIN_ERROR = 'LOGIN_ERROR';